name: main
on:
  push:
    branches:
    - main
    tags:
    - "*"
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: 'mac'
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            suffix: 'linux'
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install cmake
        uses: lukka/get-cmake@latest
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.2
          modules: 'qt5compat'
          cache: true
      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: 1.4.304.1
          vulkan-components: Vulkan-Headers
          vulkan-use-cache: true
      - name: build
        run: |
          cmake -G Ninja -B out
          cd out
          ninja
      - name: artifacts
        uses: actions/upload-artifact@main
        with:
          name: EESaveEditor-${{ matrix.suffix }}
          path: ./out/EESaveEditor
  build-win:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: 'Configure MSVC'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.2
          modules: 'qt5compat'
          cache: true
      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: 1.4.304.1
          vulkan-components: Vulkan-Headers
          vulkan-use-cache: true
      - name: build
        run: |
          cmake -G Ninja -B out
          cd out
          ninja
      - name: artifacts
        uses: actions/upload-artifact@main
        with:
          name: EESaveEditor.exe
          path: ./out/EESaveEditor.exe
  release:
    needs: [build, build-win]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - file: EESaveEditor-mac
          - file: EESaveEditor-linux
          - file: EESaveEditor.exe
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@main
        with:
          generateReleaseNotes: true
          skipIfReleaseExists: true
      - uses: actions/download-artifact@main
        with:
          name: ${{ matrix.file }}
      - name: Upload Release Asset - ${{ matrix.os }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ matrix.file }}
          asset_content_type: application/octet-stream
